HackRU/HackRU-Backend

.github/workflows/serverlessDeploy.yml, package-lock.json
- Added new workflow so that any new code to 'dev' or 'main' will trigger a new deployment to API Gateway
=> added Github Action deploy workflow script

.env.vault, .github/workflows/serverlessDeploy.yml, .gitignore, package-lock.json, package.json, src/functions/check-registration/handler.ts
try out env-vault for encrypting env. variables so that github action can decrypt and use them
=> add env-vault for serverless deploy script

serverless.ts
**Summary**
- This will help Lambda unlock .env.vault to access our env. variables
=> add DOTENV_KEY to serverless.ts file

src/functions/update/handler.ts, src/util.ts
- Adjusted logic code in update/handler so updates could be made instead of throwing errors
- Removed console.log errors while debugging
=> fixed logic code and removed console.log

serverless.ts, src/functions/index.ts, src/functions/read/handler.ts, src/functions/read/index.ts, src/functions/read/schema.ts
Read endpoint according to Ethan's spec. Awaiting tests as I don't know how to run unit tests yet.
=> Read implementation

package-lock.json, package.json, serverless.ts, src/functions/forgot-password/handler.ts, src/functions/forgot-password/index.ts, src/functions/forgot-password/schema.ts, src/functions/index.ts, tests/forgot-password.test.ts
Implemented the forgot-password endpoint which allows users to request a password reset. A 7-digit code is generated and emailed to the user through AWS SES. Valid for 15 minutes.
=> feat: forgot password endpoint

serverless.ts, src/functions/index.ts, src/functions/reset-password/handler.ts, src/functions/reset-password/index.ts, src/functions/reset-password/schema.ts, tests/reset-password.test.ts
**SUMMARY:**
- Added logic code. This endpoint will retrieve the forgot-password object and do a few checks before performing a password update. 
- Added unit tests
=> Added reset-password endpoint into 'dev' environment

src/functions/resume/handler.ts, tests/resume.test.ts
- Removed checkIfFileExist functionality. If a new file is uploaded, the old pdf will be overwritten with the newest addition. No versioning necessary.
- Updated unit tests accordingly.
=> Resume new feature: updated logic code and fixed unit tests

src/functions/resume/handler.ts, src/functions/waiver/handler.ts
- Added a new field **hasUploaded:true** in the response body of the endpoint **resume** and **waiver**. This is to allow frontend to see if the user has uploaded a resume/waiver before
=> Added new field in resume and waiver response body

src/functions/attend-event/handler.ts, src/functions/attend-event/schema.ts, tests/attend-event.test.ts
Implemented points in the `attend-event` endpoint as per issue #56 
**BREAKING CHANGE:** `again` was removed and replaced with `limit`, which is required
=> feat: implement points in attend-event

src/functions/attend-event/handler.ts
=> feat: add name fields to points db

serverless.ts, src/functions/get-buy-ins/handler.ts, src/functions/get-buy-ins/index.ts, src/functions/get-buy-ins/schema.ts, src/functions/index.ts, tests/get-buy-ins.test.ts
=> feat: get-buy-ins endpoint

src/functions/attend-event/handler.ts
=> feat(attend-event): return attendance count

src/config.ts
- Changed dates to open up registration for spring hackathon (allows account creation)
=> open registration for spring hackathon

serverless.ts, src/functions/create/handler.ts, src/functions/index.ts, src/functions/update/handler.ts, src/functions/verify-email/handler.ts, src/functions/verify-email/index.ts, src/functions/verify-email/schema.ts, src/util.ts, tests/verify-email.test.ts
Added `verify-email` endpoint to facilitate email verification.
=> feat: verify-email endpoint

src/functions/attend-event/handler.ts, src/functions/get-buy-ins/handler.ts, src/functions/leaderboard/handler.ts, src/functions/points/handler.ts, src/functions/update-buy-ins/handler.ts
- removed the old collection name and added a new one for the points system for spring 25 hackathon
=> new points collection for s25 hackathon

src/functions/update/handler.ts, tests/update.test.ts
- turned off notify-user-registration-status feature for now
- updated unit test accordingly (update.test.ts)
=> turned off notify-user-registration-status feature 

src/functions/interest-form/schema.ts
Removed the 'uri' requirement from the schema.tsx of the interest form endpoint
=> Hotfix: Interest Form URI Requirement

tests/interest-form.test.ts
Initially forgot to update the unit tests
=> Updated tests to include checking of submittedAt time

src/functions/teams/create/handler.ts
having the invite call within the transaction caused failure. Moved it out of the transaction to remedy this error.
=> Moved invite call out of transaction

src/functions/teams/create/handler.ts
=> Bug: Team Creation allows self
